#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "motioneye"
name = "motionEye"
description.en = "A interface for the software motion, a video surveillance program with motion detection"

version = "0.43.1b1~ynh1"

maintainers = ["solazdev"]

[upstream]
license = "GPL-3.0"
userdoc = "https://github.com/motioneye-project/motioneye/wiki"
code = "https://github.com/motioneye-project/motioneye"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "500M"
ram.build = "512M"
ram.runtime = "1024M"

[install]
    [install.domain]
    type = "domain"

    # [install.path]
    # type = "path"
    # default = "/motioneye"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    # [install.password]
    # # this is a generic question - ask strings are automatically handled by YunoHost's core
    # # Note that user-provided passwords questions are not automatically saved as setting
    # help.en = "Use the help field to add an information for the admin about this question."
    # help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    # type = "password"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/motioneye-project/motioneye/archive/refs/tags/0.43.1b1.tar.gz"
        sha256 = "4eb191029a142f11f4c30cf558e2552ea4b9d659aee54cb65a5e7e4f6f56bd11"
        extract = false
        rename = "source.tar.gz"
        # autoupdater temporarily disabled, waiting for 0.43.1 final release (python 3 support)
        # autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    subdirs = ["media"]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 8765

    [resources.apt]
    packages = "ca-certificates, curl, python3, python3-dev, python3-venv, libcurl4-openssl-dev, gcc, libssl-dev, motion, ffmpeg, v4l-utils, libssl-dev, libcurl4-openssl-dev, libjpeg-dev, zlib1g-dev, libffi-dev, libzbar-dev, libzbar0"
